# Generated by Django 5.0.4 on 2024-05-07 05:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=60, verbose_name='Nombre(s)')),
                ('lastName', models.CharField(max_length=60, verbose_name='Apellido(s)')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('passW', models.CharField(max_length=100, verbose_name='Contraseña')),
                ('photo', models.ImageField(blank=True, upload_to='media/user', verbose_name='Fotografia')),
                ('createAt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha De Creacion')),
            ],
        ),
    ]
