# Generated by Django 5.0.4 on 2024-05-07 05:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('archive', models.FileField(upload_to='media/archive')),
                ('createAt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha De Creacion')),
                ('likes', models.ManyToManyField(blank=True, related_name='archive_liked', to='user.user')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('createAt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha De Creacion')),
                ('archive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repo.archive')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
