# Generated by Django 5.0.4 on 2024-05-07 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='archive',
            field=models.FileField(blank=True, upload_to='archive'),
        ),
    ]
